const JournalActionTypes = {
    FETCH_JOURNAL_START: 'FETCH_JOURNAL_START',
    FETCH_JOURNAL_SUCCESS: 'FETCH_JOURNAL_SUCCESS',
    FETCH_JOURNAL_FAILURE: 'FETCH_JOURNAL_FAILURE',
    CLEAR_FETCH_FAILURE: 'CLEAR_FETCH_FAILURE',
    ADD_ENTRY_START: 'ADD_ENTRY_START',
    ADD_ENTRY_SUCCESS: 'ADD_ENTRY_SUCCESS',
    ADD_ENTRY_FAILURE: 'ADD_ENTRY_FAILURE',
    CLEAR_ADD_FAILURE: 'CLEAR_ADD_FAILURE',
    DELETE_ENTRY_START: 'DELETE_ENTRY_START',
    DELETE_ENTRY_SUCCESS: 'DELETE_ENTRY_SUCCESS',
    DELETE_ENTRY_FAILURE: 'DELETE_ENTRY_FAILURE',
    CLEAR_DELETE_FAILURE: 'CLEAR_DELETE_FAILURE',
    UPDATE_ENTRY_START: 'UPDATE_ENTRY_START',
    UPDATE_ENTRY_SUCCESS: 'UPDATE_ENTRY_SUCCESS',
    UPDATE_ENTRY_FAILURE: 'UPDATE_ENTRY_FAILURE',
    CLEAR_UPDATE_FAILURE: 'CLEAR_UPDATE_FAILURE',
    SET_JOURNAL_FILTER: 'SET_JOURNAL_FILTER',
    CLEAR_JOURNAL_FILTER: 'CLEAR_JOURNAL_FILTER'
}

export default JournalActionTypes;