const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    FETCH_USER_LIST_START: 'FETCH_USER_LIST_START',
    FETCH_USER_LIST_SUCCESS: 'FETCH_USER_LIST_SUCCESS',
    FETCH_USER_LIST_FAILURE: 'FETCH_USER_LIST_FAILURE',
    CLEAR_USER_LIST_FETCH_FAILURE: 'CLEAR_USER_LIST_FETCH_FAILURE',
}

export default UserActionTypes;